### ISSUE TITLE
Add support for Alloc's server fixes

### ISSUE THREAD

**Issue by cliffrowley** [zobees/docker-7daystodie#1]
https://7dtd.illy.bz/wiki/Server%20fixes

**Comment by mindrunner** [comment]
I am using this extension. Just copy it to your mods folder and you are good to go.

**Comment by cliffrowley** [comment]
Yep, my plan is to at some point (when time allows) to allow the image to automatically download and set up some mods and fixes etc. Thanks :)

**Comment by cliffrowley** [comment]
Closing this until it comes back again.
