### ISSUE TITLE
A19 breaks initialization of server

### ISSUE THREAD

**Issue by jcoker85** [zobees/docker-7daystodie#3]
Alpha 19 breaks the initialization of the server. In the 7dtd-server script the -logfile /dev/stdout parameter no longer works due to the removal of that directory or a permissions issue. I did not look into why but just removed the -logfile parameter from this script and rebuilt the image. 

I know this is old but wanted to post this here in case it helps anyone else.

**Comment by cliffrowley** [comment]
Thanks, appreciated! I haven't had a chance to update this in a while, but you've successfully prompted me to take a look at it again.

**Comment by mitchjam** [comment]
@jcoker85 Would you mind giving a quick explanation of how you did that here?

**Comment by jcoker85** [comment]
@mitchjam Sure. Here are the basic steps:

1. Download ZIP archive of this repo
2. Extract archive
2. In the extracted folder, open the 7dtd-server file and remove line 10: **"-logfile /dev/stdout \ "** 
3. Build the modified image: **docker build -t your_name/your_image** in the directory of the Dockerfile 
4. Use **docker run** command as normally but with your_name/your_image instead of zobees/7daystodie

These are from memory, so you may have to fiddle a bit to get everything working.

**Comment by cliffrowley** [comment]
I've dropped the `-logfile` from the command line and pushed the latest image. If I get a chance I'll look into it further, but this should at least fix it for now. Thanks again!
